
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: HelmDeploy@0
  displayName: 'helm upgrade'
  inputs:
    azureSubscription: 'june-9_test-for-sub'
    azureResourceGroup: 'AKS-RG'
    kubernetesCluster: 'pricing-api'
    namespace: default
    command: upgrade
    chartType: FilePath
    chartPath: helmchart
    releaseName: pricingapi
    valueFile: helmchart/values.yaml   
- script: |
    curl -X POST \
      -H "Authorization: Bearer $(PAT)" \
      -H "Content-Type: application/json" \
      -d '{
            "body": "This is a comment on the pull request"
         }' \
      https://api.github.com/repos/Tivona-Internal/pricing_api/issues/$(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)/comments
  displayName: 'Post PR Comment'
