trigger: none
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self

  - task: Docker@2
    displayName: 'Pricingapi_Image_Build'
    inputs:
      containerRegistry: logaacr
      repository: pricingapptest
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: |
        latest
