# Generated by Django 4.1.7 on 2023-04-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='region',
            old_name='displayname',
            new_name='display_name',
        ),
    ]
