# Generated by Django 4.1.7 on 2023-04-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_api', '0002_alter_region_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='zones',
            new_name='availability_zones',
        ),
    ]
