# Generated by Django 4.1.7 on 2023-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_api', '0004_remove_benchmark_vmsizes_benchmark_vmbenchrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtier',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
