# Generated by Django 4.1.7 on 2023-05-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_api', '0005_vmtier_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VmSizes',
            new_name='VmSku',
        ),
    ]
