# Generated by Django 4.1.7 on 2023-05-23 07:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_api', '0006_rename_vmsizes_vmsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_regional_price_models',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('vm_tier', models.CharField(max_length=100)),
                ('price_plan', models.CharField(max_length=100)),
                ('best_price', models.CharField(max_length=100)),
                ('best_price_region', models.CharField(max_length=100)),
                ('effectivestartdate', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricing',
            name='Meter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pricing',
            name='OperatingSystem',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='ACUs',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='AcceleratedNetworkingEnabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CachedDiskBytes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CapacityReservationSupported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CombinedTempDiskAndCachedIOPS',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CombinedTempDiskAndCachedReadBytesPerSecond',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CombinedTempDiskAndCachedWriteBytesPerSecond',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='ConfidentialComputingType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='CpuArchitectureType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='DiskControllerTypes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='EncryptionAtHostSupported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='EphemeralOSDiskSupported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='GPUs',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='HibernationSupported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='HyperVGenerations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='LowPriorityCapable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='MaxDataDiskCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='MaxNetworkInterfaces',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='MaxResourceVolumeMB',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='MaxWriteAcceleratorDisksAllowed',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='MemoryPreservingMaintenanceSupported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='NvmeDiskSizeInMiB',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='OSVhdSizeMB',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='ParentSize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='PremiumIO',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='RdmaEnabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='TrustedLaunchDisabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='UltraSSDAvailable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='UncachedDiskBytesPerSecond',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='UncachedDiskIOPS',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='VMDeploymentTypes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='vCPUsAvailable',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vmsku',
            name='vCPUsPerCore',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='MemoryGB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='vCPUs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='vm_sku_details',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='vmsku',
            name='vm_sku_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
