apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - data:
    - objectName: clientid
      key: clientid
    - objectName: clientsecret
      key: clientsecret  
    - objectName: dbhost
      key: dbhost
    - objectName: dbname
      key: dbname   
    - objectName: dbpassword
      key: dbpassword 
    - objectName: subscriptionid
      key: subscriptionid
    - objectName: tenant
      key: tenant 
    - objectName: dbuser
      key: dbuser   
    secretName: akvsecrets
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "372c6e88-4dec-4c0b-aa54-0a8da7e5fc8a" # Kubelet Client Id ( Nodepool Managed Idendity )
    keyvaultName: "pricingsecrets" # the name of the KeyVault
    tenantId: "75f2a99b-01fd-48f2-ac60-d4a7a44fd0cc" # the tenant ID of the KeyVault  
    objects:  |
      array:
        - |
          objectName: clientid
          objectAlias: clientid
          objectType: secret
        - |
          objectName: clientsecret
          objectAlias: clientsecret
          objectType: secret
        - |
          objectName: dbhost
          objectAlias: dbhost
          objectType: secret
        - |
          objectName: dbname
          objectAlias: dbname
          objectType: secret
        - |
          objectName: dbpassword
          objectAlias: dbpassword
          objectType: secret
        - |
          objectName: subscriptionid
          objectAlias: subscriptionid
          objectType: secret
        - |
          objectName: tenant
          objectAlias: tenant
          objectType: secret
        - |
          objectName: dbuser
          objectAlias: dbuser
          objectType: secret
